# Generated by Django 4.2.7 on 2025-10-23 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_user_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('group_id', models.CharField(max_length=100)),
                ('brand', models.CharField(db_index=True, max_length=50)),
                ('subscribed', models.BooleanField(db_index=True, default=True)),
                ('allowed_from_group', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscribed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscribers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['brand', 'subscribed', 'allowed_from_group'], name='subscribers_brand_a518fb_idx'), models.Index(fields=['created_at'], name='subscribers_created_d14985_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClickLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(max_length=100)),
                ('vk_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('group_id', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='app.subscriber')),
            ],
            options={
                'db_table': 'click_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
