# Generated by Django 4.2.7 on 2025-10-23 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=200, verbose_name='Название партнёра')),
                ('logo_url', models.URLField(max_length=500, verbose_name='URL логотипа')),
                ('sum_min', models.IntegerField(verbose_name='Минимальная сумма, ₽')),
                ('sum_max', models.IntegerField(verbose_name='Максимальная сумма, ₽')),
                ('term_min', models.IntegerField(verbose_name='Минимальный срок, дней')),
                ('term_max', models.IntegerField(verbose_name='Максимальный срок, дней')),
                ('rate', models.FloatField(verbose_name='Ставка (% в день)')),
                ('rate_text', models.CharField(help_text='Например: "0.5% в день"', max_length=100, verbose_name='Ставка (текст)')),
                ('approval_time', models.CharField(help_text='Например: "15 минут"', max_length=100, verbose_name='Время одобрения')),
                ('approval_probability', models.CharField(choices=[('высокая', 'Высокая'), ('средняя', 'Средняя'), ('низкая', 'Низкая')], max_length=50, verbose_name='Вероятность одобрения')),
                ('features', models.JSONField(default=list, help_text='Список особенностей, например: ["Без отказа", "Первый займ 0%"]', verbose_name='Особенности')),
                ('redirect_url', models.URLField(help_text='Используйте {sub_id} для подстановки идентификатора', max_length=1000, verbose_name='URL для перехода')),
                ('is_active', models.BooleanField(default=True, help_text='Неактивные офферы не показываются пользователям', verbose_name='Активен')),
                ('priority', models.IntegerField(default=0, help_text='Чем выше число, тем выше в списке', verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Оффер',
                'verbose_name_plural': 'Офферы',
                'db_table': 'offers',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='clicklog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Клик по офферу', 'verbose_name_plural': 'Клики по офферам'},
        ),
        migrations.RemoveField(
            model_name='clicklog',
            name='offer_id',
        ),
        migrations.AlterField(
            model_name='clicklog',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='clicklog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата клика'),
        ),
        migrations.AlterField(
            model_name='clicklog',
            name='group_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Group ID'),
        ),
        migrations.AlterField(
            model_name='clicklog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='clicklog',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='app.subscriber', verbose_name='Подписчик'),
        ),
        migrations.AlterField(
            model_name='clicklog',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='clicklog',
            name='vk_user_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='VK User ID'),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='app.offer', verbose_name='Оффер'),
        ),
    ]
