# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_appconfig_sort_buttons'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='card_gradient_start',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Градиент карточек: начало'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='card_gradient_end',
            field=models.CharField(default='#F9FAFB', max_length=7, verbose_name='Градиент карточек: конец'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='card_gradient_enabled',
            field=models.BooleanField(default=False, verbose_name='Включить градиент карточек'),
        ),
    ]

