FROM node:18-alpine as builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# Используем .env.mobile файл для мобильной версии
COPY .env.mobile .env
ARG VITE_API_BASE
ARG VITE_PLATFORM=mobile
ENV VITE_API_BASE=$VITE_API_BASE
ENV VITE_PLATFORM=$VITE_PLATFORM
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
