version: '3.8'

# Development override для локальной разработки
services:
  backend:
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_DEBUG=True
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      target: builder
    command: npm run dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE=http://localhost:8000

