# Generated by Django for adding header_caption field

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_appconfig_vk_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='header_caption',
            field=models.CharField(default='Лучшие предложения', max_length=200, verbose_name='Надпись под хедером'),
        ),
    ]
